  CREATE MULTISET TABLE P_hang_T.table2 AS (
  SELECT 
  HOT.A,
  HOT.B,
  HOT.C,
  HOT.AUCT_END_DT,
  HOT.AUCT_START_DT,
  
  FROM table1 AS HOT

  WHERE     1 = 1
  AND       HOT.AUCT_END_DT >= DATE '2017-01-01'
  AND       HOT.AUCT_START_DT BETWEEN DATE '2017-01-01' AND DATE '2017-01-28'
  )WITH DATA         